### ISSUE TITLE
Al agregar un producto al carrito e intentar confirmar compra marca error en la consola

### ISSUE THREAD

**Issue by geronm12** [nicopowell/proyectoMERN#70]
### SITUACION ACTUAL
Ingresar al sitio web como un usario sin iniciar sesión (sin registro previo), agregar un producto al carrito, luego dirigirse al carrito y hacer click en el botón confirmar compra.

**RESULTADO OBTENIDO**
Error en la consola y el sistema no indica al usuario  sobre dicho error.

**RESULTADO ESPERADO**
El sistema debería evitar que el usuario pueda comprar cosas si es obligatorio que esté registrado o debería poder confirmar la compra correctamente (en caso de no ser obligatorio el registro previo)

![image](https://github.com/nicopowell/proyectoMERN/assets/44532299/888430a2-3866-4ab2-8d26-4aa5e6456e67)

https://github.com/nicopowell/proyectoMERN/assets/44532299/bfed24af-8097-484e-b427-ba8562682765

**Comment by nicopowell** [comment]
Corregido en la rama hotfix-errorConfirmarPedido
