### ISSUE TITLE
Validaciones Innecesarias

### ISSUE THREAD

**Issue by geronm12** [nicopowell/proyectoMERN#71]
### SITUACION ACTUAL
Ingresar como un usuario administrador, dirigirse a algun producto/menu para editar, modificar el precio por un monto mayor a 10.000

![image](https://github.com/nicopowell/proyectoMERN/assets/44532299/e7ce6219-5205-45a4-873b-b43a14d56231)

**RESULTADO OBTENIDO** 
El sistema no me permite ingresar un monto mayor a 10.000 

**RESULTADO ESPERADO**
El sistema debería permitir que el usuario pueda ingresar valores hasta n (infinito) siempre y cuando no sean negativos. Esto debido a que nosotros no podemos forzar a que el usuario si o si asigne un precio dentro de  un rango (si quisiera que la pizza de mi local cueste 12.500 no podría usar el sistema).

**Comment by nicopowell** [comment]
Se corrigió en la rama hotfix-validacionesInnecesarias
