### ISSUE TITLE
Un pedido con estado entregado no se debería poder cancelar ni borrar

### ISSUE THREAD

**Issue by geronm12** [nicopowell/proyectoMERN#72]
### SITUACION ACTUAL
Como usuario tipo administrador, ingresar a la solapa de pedidos dentro de la administración. Buscar un pedido que se encuentre
en estado "entregado", se podrá observar que tenemos 2 botones (cancelar y borrar).

![image](https://github.com/nicopowell/proyectoMERN/assets/44532299/cd28ea1f-33ac-4669-a1ce-5e7631bb22d5)

**RESULTADO OBTENIDO**
Ambos botones me permiten interactuar con el pedido que ya se encuentra "entregado"

**RESULTADO ESPERADO**
Asumiendo que el estado "entregado" se aplica a la vida real, es decir, un pedido que se encuentra "entregado" ya está en manos de el cliente no se debería poder interactuar (cancelarlo o borrarlo) porque si dicho pedido tuvo un impacto en el monto de ganancias del día podemos tener problemas con la consistencia de los datos en la base (tendriamos una caja que no cierra porque un pedido que fue "entregado" y fue cobrado se está "restando" de los ingresos puesto que se canceló.

**Comment by nicopowell** [comment]
Corregido en la rama hotfix-pedidosEntregados
