### ISSUE TITLE
Inconsistencia en los mensajes y labels

### ISSUE THREAD

**Issue by geronm12** [nicopowell/proyectoMERN#73]
### SITUACION ACTUAL 

Como un usuario administrador ingresar al sitio y acceder a las solapas de administración (pedidos, usuarios, menu).
Podremos observar que el botón indica la leyenda "borrar" mientras todos los mensajes del pop up  indica la leyenda "eliminar"

**Pedidos:** 

![image](https://github.com/nicopowell/proyectoMERN/assets/44532299/54a18595-8844-481f-a4bc-2f89224288d5)

![image](https://github.com/nicopowell/proyectoMERN/assets/44532299/15363648-ffd9-40cb-9a73-f1795d478bb3)

**Menu:**

![image](https://github.com/nicopowell/proyectoMERN/assets/44532299/79e286ff-834a-4f08-a446-94a6d364e32b)

![image](https://github.com/nicopowell/proyectoMERN/assets/44532299/3593c4e7-8bc4-41cd-a64b-f07788d2e9c2)

**RESULTADO OBTENIDO** 
Los mensajes no son consistentes puesto que se utilizan distintas formas de llamar a los mismos procesos y puede ser confuso para el usuario.

**RESULTADO ESPERADO**
Los mensajes y labels deberían tener consistencia para evitar la posible confusión del usuario.

**Comment by nicopowell** [comment]
Se corrigió en la rama hotfix-inconsistenciaMensajes
