### ISSUE TITLE
Un pedido cancelado no debería volver a estado "Pendiente"

### ISSUE THREAD

**Issue by geronm12** [nicopowell/proyectoMERN#74]
### SITUACION ACTUAL
Ingresar como un usuario de tipo administrador, dirigirse a la solapa de pedidos. Hacer click en cancelar un pedido.

![image](https://github.com/nicopowell/proyectoMERN/assets/44532299/26a0a99f-b330-44ef-bce7-ddb4007e3d25)

![image](https://github.com/nicopowell/proyectoMERN/assets/44532299/ebb934d3-c92a-4c8d-9b8a-fef9088ce8c3)

https://github.com/nicopowell/proyectoMERN/assets/44532299/435961f1-ddb8-45d1-89c0-abd79116c096

**RESULTADO OBTENIDO**
El pedido pasa a estar en estado "Pendiente"

**RESULTADO ESPERADO**
Al cancelar un pedido, el mismo debería pasar a estado "Cancelado" y no permitir que se pueda confirmar nuevamente. Si el usuario canceló su pedido o el admin decide cancelar el pedido, en caso de querer uno nuevo se debe crear otro diferente (para mantener auditoría y registro de los distintos movimientos que sucedieron en los procesos internos)

**Comment by nicopowell** [comment]
Se corrigio en la rama hotfix-pedidoCancelado
